"""empty message

Revision ID: 740ff2bb092c
Revises: e2c7d2bcd81b
Create Date: 2022-04-07 14:53:31.250097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740ff2bb092c'
down_revision = 'e2c7d2bcd81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Post', 'title',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Post', 'title',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    # ### end Alembic commands ###
