"""empty message

Revision ID: e2c7d2bcd81b
Revises: 5f248328d278
Create Date: 2022-04-07 14:39:16.231754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c7d2bcd81b'
down_revision = '5f248328d278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'avatar_url',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=60),
               existing_nullable=True,
               existing_server_default=sa.text("'/static/img/default.png'::character varying"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'avatar_url',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True,
               existing_server_default=sa.text("'/static/img/default.png'::character varying"))
    # ### end Alembic commands ###
